### ISSUE TITLE
System hangs out & then crashed

### ISSUE THREAD

**Issue by JustDevZero** [AsydSolutions/ASYD#105]
On devel branch, after adding a new host it doesn't deploy neither monit neither the files... :/

It's just crashing somehow (too late to check by my self). Trying to delete the host, to restart everything again also goes to a 500 error.

In the logs appears this:

E, [2015-08-30T06:01:26.501697 #4466] ERROR -- : worker=0 PID:5043 timeout (61s > 60s), killing
E, [2015-08-30T06:01:26.504827 #4466] ERROR -- : reaped #<Process::Status: pid 5043 SIGKILL (signal 9)> worker=0
I, [2015-08-30T06:01:26.513088 #5233]  INFO -- : worker=0 ready
127.0.0.1 - - [30/Aug/2015:06:01:26 +0200] "GET /api/ping HTTP/1.1" 200 4 0.0238
127.0.0.1 - - [30/Aug/2015:06:01:26 +0200] "GET /api/ping HTTP/1.1" 200 4 0.0009
127.0.0.1 - - [30/Aug/2015:06:01:26 +0200] "GET /api/ping HTTP/1.1" 200 4 0.0008
2015-08-30 06:02:26 - Errno::EINTR - Interrupted system call - error in sem_wait:
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/process_shared-0.2.1/lib/process_shared/posix/errno.rb:28:in `block (2 levels) in error_check'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/process_shared-0.2.1/lib/process_shared/posix/semaphore.rb:88:in `wait'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/process_shared-0.2.1/lib/process_shared/mutex.rb:38:in `lock'
        /home/zero/Projectes/ASYD/models/lib/asyd-wal.rb:18:in `synchronize'
        /home/zero/Projectes/ASYD/routes/host.rb:44:in `block in <class:ASYD>'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/tempfile_reaper.rb:15:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/chunked.rb:54:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:580:in `process_client'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/unicorn-worker-killer-0.4.3/lib/unicorn/worker_killer.rb:92:in `process_client'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:674:in `worker_loop'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:529:in `spawn_missing_workers'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:540:in `maintain_worker_count'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:294:in `join'
        /home/zero/Projectes/ASYD/vendors/.gem/ruby/2.2.2/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'

**Comment by JustDevZero** [comment]
I'm closing, this will be fixed with my new pull-request coming this night.

It happens, because the terminal ask for tty (requiretty), but the prompt shows:
"Contraseña" instead of the usual "[sudo] password for user"
