### ISSUE TITLE
[faq] Troubleshooting

### ISSUE THREAD

**Issue by Choms** [AsydSolutions/ASYD#81]
**Q.** On Ruby 2.2.0, sometimes after upgrading ASYD you can get this error message:
`dm-serializer-1.2.2/lib/dm-serializer/to_yaml.rb:15:in 'included': undefined method 'add_domain_type' for Psych:Module (NoMethodError)`

**A.** Reinstall those gems:
`gem uninstall data_mapper dm-serializer sinatra`
`bundle install`

**Comment by Choms** [comment]
**Q.** ASYD won't start with error: **.gem/ruby/gems/ffi-1.9.8/lib/ffi/library.rb:133:in `block in ffi_lib': Could not open library '.gem/ruby/gems/process_shared-0.2.0/lib/process_shared/posix/helper.so'**

**A.** process_shared has an issue building (at least on) Fedora systems, on which doesn't installs helper.so on the correct directory. This is already reported on pmahoney/process_shared#4 

One workaround is to find where this file is located (`find .gem/ |grep helper.so`) and link it (`ln -s`) to `.gem/ruby/gems/process_shared-0.2.0/lib/process_shared/posix/helper.so`

**Comment by Choms** [comment]
**Q.** When adding a host which displays "-bash: warning: setlocale: LC_ALL: cannot change locale" when ssh-ing to it (no locales package installed), the frontend throws a stacktrace. 

**A.** Once installing the necessary packages and configuring locales correctly with the below commands, adding a host works without problems.

```
apt-get update
apt-get -y install locales
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
echo "#  File generated by update-locale" > /etc/default/locale
locale-gen
update-locale
```

**Comment by fbrandstetter** [comment]
It looks like this now:

root@10.0.5.7's password:100.64.12.1 - - [21/Oct/2016:20:12:46 +0100] "POST /host/add HTTP/1.1" 303 - 7.3459

**Comment by fbrandstetter** [comment]
After installing HighLine, I'm getting:

root@10.0.5.7's password: stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device

root@10.0.5.7's password: stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device

root@10.0.5.7's password: stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device

100.64.12.1 - - [21/Oct/2016:20:21:59 +0100] "POST /host/add HTTP/1.1" 303 - 10.2078

**Comment by Choms** [comment]
That's not exactly what I expected but it rings a bell, there was a similar bug a while ago, the "ioctl" part is quite disconcerting though. I'll take a deeper look in the morning.

**Comment by fbrandstetter** [comment]
Maybe some dependencies are missing on my brand new installation of Jessie.

**Comment by fbrandstetter** [comment]
After hours of debugging now, I've finally brought it to that issue:

Error adding the host FRANKFURT: Authentication failed for user root@<HIDDEN_IP>

**Comment by Choms** [comment]
Hi again,

The last error is just a common auth failure message (wrong user/password, careful about the spaces if you are copypasting the password, etc.)

About the actual issue, the ioctl thing, looks like some stty configuration is messing things up with the net-ssh connector (on the setup it opens a stream to the machine so it can send/receive interactively to verify that the permissions for the user are all correct). I've tested on a fresh Debian 8.5 minimal installation (to be specific a vultr instance) and works just fine out of the box, so dependencies should not be an issue. Can you check your .bashrc and see if you have any stty line that might be changing the default behavior and causing this issue?

Cheers!

**Comment by JustDevZero** [comment]
@fbrandstetter Be sure that in /etc/ssh/sshd_config the line:
PermitRootLogin is set to YES or atleast to without-password (if the ssh key was already there).

**Comment by fbrandstetter** [comment]
Hello Choms,

The .bashrc was the issue! I've had some fancy .bashrc in order to make putty look a bit better, although this destroyed things. I've switched back to the default .bashrc from Debian and it works like a charm.


Thanks for your assistance and thank you for this product! :-)

**Comment by Choms** [comment]
You are welcome :) Do you mind telling me which was the setting causing the issue so I can further debug it when I have some time?

**Comment by fbrandstetter** [comment]
This is the .bashrc I used:
https://paster.li/?c12de4359587af91#EydO79iw5avB3jWXyxB/+xxr7Gdk/O/UM+fkXENlrLk=

Keep in mind: burns after first read, so save it :)

**Comment by Choms** [comment]
lol it was already expired, just email me at sergio@asyd-solutions.com

**Comment by Choms** [comment]
I'm cleaning up a bit this thread (it's the troubleshooting one after all).
